# Generated by Django 3.1.7 on 2021-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210323_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
