# Generated by Django 3.1.7 on 2021-04-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210413_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
