# Generated by Django 3.1.7 on 2021-03-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phnumber', models.IntegerField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('rating', models.CharField(choices=[('Unrated', 'Unrated'), ('Bad', 'Bad'), ('Satissfactory', 'Satisfactory'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Unrated', max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='city.city')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
    ]
