# Generated by Django 3.1.7 on 2021-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='veg_only',
            field=models.BooleanField(default=False),
        ),
    ]
