# Generated by Django 3.1.7 on 2021-04-07 09:45

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210322_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.location),
        ),
    ]
