# Generated by Django 3.1.7 on 2021-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210417_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='restaurantrating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 'Unrated'), (1, 'Bad'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Excellent')], default='Unrated', null=True),
        ),
    ]
