# Generated by Django 3.1.7 on 2021-03-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
