# Generated by Django 3.1.7 on 2021-04-07 09:34

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210323_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.location),
        ),
    ]
