# Generated by Django 3.1.7 on 2021-04-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
