# Generated by Django 3.1.7 on 2021-04-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0008_auto_20210413_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Unrated', 'Unrated'), ('Bad', 'Bad'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Unrated', max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
