# Generated by Django 3.1.7 on 2021-04-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0010_auto_20210417_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 'Unrated'), (1, 'Bad'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Excellent')], default='Unrated', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'item')},
        ),
    ]
