# Generated by Django 3.2 on 2021-04-28 12:05

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20210428_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='/default/itemDefault.png', null=True, upload_to=menu.models.location),
        ),
    ]
