# Generated by Django 3.2 on 2021-04-29 08:44

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='default/itemDefault.png', upload_to=menu.models.location),
        ),
    ]
