# Generated by Django 3.2 on 2021-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210428_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Received'), (3, 'Placed'), (4, 'Out for Delivery'), (5, 'Delivered')], default=1),
        ),
    ]
