# Generated by Django 3.1.7 on 2021-03-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0006_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.userorder'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='itemname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to='menu.menu'),
        ),
    ]
