# Generated by Django 3.1.7 on 2021-03-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210321_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='userorder',
        ),
    ]
