# Generated by Django 3.1.7 on 2021-03-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210321_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staffuser',
        ),
    ]
