# Generated by Django 3.1.7 on 2021-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_staffuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
