# Generated by Django 3.1.7 on 2021-03-23 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210323_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='userorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
