# Generated by Django 3.1.7 on 2021-03-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210323_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorder',
            options={'ordering': ['-updated']},
        ),
    ]
