# Generated by Django 3.1.7 on 2021-03-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210323_1158'),
        ('order', '0018_auto_20210323_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.userorder'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to='menu.menu'),
        ),
    ]
