# Generated by Django 3.1.7 on 2021-03-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210323_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userorder',
            new_name='user_order',
        ),
    ]
