# Generated by Django 3.1.7 on 2021-03-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210323_1158'),
        ('order', '0022_auto_20210323_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='order.userorder'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menu'),
        ),
    ]
