# Generated by Django 3.1.7 on 2021-04-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_userorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
