# Generated by Django 3.1.7 on 2021-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_userorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
