# Generated by Django 3.1.7 on 2021-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20210412_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='price',
        ),
    ]
