# Generated by Django 3.1.7 on 2021-04-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_userorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
