# Generated by Django 3.1.7 on 2021-04-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
