# Generated by Django 3.1.7 on 2021-04-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
