# Generated by Django 3.1.7 on 2021-04-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_remove_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user_order',
        ),
    ]
