# Generated by Django 3.1.7 on 2021-04-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
