# Generated by Django 3.1.7 on 2021-04-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210413_1139'),
        ('order', '0043_auto_20210413_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='userorder',
            name='deliver_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.delivery'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='menu.menu'),
        ),
    ]
