# Generated by Django 3.1.7 on 2021-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20210416_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
